// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYmWvjoOREXWRC5pmQAhzBzMzwI5fOw-8',
    appId: '1:963234946905:web:e24e3bc8a82785e7cbf648',
    messagingSenderId: '963234946905',
    projectId: 'trabajo-final-2307d',
    authDomain: 'trabajo-final-2307d.firebaseapp.com',
    storageBucket: 'trabajo-final-2307d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLRV17bukZ8a2ASg8-ZCUP7gbCGMwFXdg',
    appId: '1:963234946905:android:d88fc374c8c0a16fcbf648',
    messagingSenderId: '963234946905',
    projectId: 'trabajo-final-2307d',
    storageBucket: 'trabajo-final-2307d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB1qGGEvxx9wYvpUx5MI_rnicI6_i3Dl4',
    appId: '1:963234946905:ios:e811ea738482155bcbf648',
    messagingSenderId: '963234946905',
    projectId: 'trabajo-final-2307d',
    storageBucket: 'trabajo-final-2307d.firebasestorage.app',
    iosBundleId: 'com.example.miAppFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB1qGGEvxx9wYvpUx5MI_rnicI6_i3Dl4',
    appId: '1:963234946905:ios:e811ea738482155bcbf648',
    messagingSenderId: '963234946905',
    projectId: 'trabajo-final-2307d',
    storageBucket: 'trabajo-final-2307d.firebasestorage.app',
    iosBundleId: 'com.example.miAppFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYmWvjoOREXWRC5pmQAhzBzMzwI5fOw-8',
    appId: '1:963234946905:web:0c72dfea5467ae59cbf648',
    messagingSenderId: '963234946905',
    projectId: 'trabajo-final-2307d',
    authDomain: 'trabajo-final-2307d.firebaseapp.com',
    storageBucket: 'trabajo-final-2307d.firebasestorage.app',
  );
}
